import { forwardRef } from 'react'
import { formatMoney, getCountry, getCurrency } from '../data/vatRates'

// Mandatory disclaimer that must appear on every generated PDF footer.
export const PDF_DISCLAIMER =
  'This invoice was generated by BillBox (mybillbox.co) for reference only. BillBox does not provide tax, legal, or accounting advice. Please verify all details with your local tax authority.'

// Visual invoice preview rendered in the DOM (also used as the PDF source).
const InvoicePreview = forwardRef(function InvoicePreview({ invoice, profile }, ref) {
  const country = getCountry(invoice.country_code)
  const currency = getCurrency(invoice.country_code)
  const subtotal = (Number(invoice.quantity) || 0) * (Number(invoice.unit_price) || 0)
  const vatAmount = subtotal * (Number(invoice.vat_rate) || 0) / 100
  const total = subtotal + vatAmount

  return (
    <div
      ref={ref}
      className="mx-auto w-full max-w-[800px] bg-white p-10 text-slate-800"
      style={{ fontFamily: 'Inter, sans-serif' }}
    >
      {/* Header */}
      <div className="flex items-start justify-between border-b border-slate-200 pb-6">
        <div className="flex items-start gap-4">
          {profile?.logo_url ? (
            <img src={profile.logo_url} alt="logo" className="h-16 w-16 rounded-lg object-cover" />
          ) : (
           <img
  src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='56' height='56'%3E%3Crect width='56' height='56' rx='8' fill='%231e3a5f'/%3E%3Ctext x='28' y='37' font-size='24' font-weight='bold' fill='white' text-anchor='middle'%3EB%3C/text%3E%3C/svg%3E"
  alt="B"
  width="56"
  height="56"
  style={{ display: 'block', borderRadius: '8px' }}
/>
          )}
          <div>
            <h2 className="text-xl font-bold text-brand">{profile?.company_name || 'Your Company'}</h2>
            <p className="mt-1 max-w-xs text-sm text-slate-500">{profile?.address || ''}</p>
            {profile?.vat_number && (
              <p className="text-sm text-slate-500">VAT: {profile.vat_number}</p>
            )}
          </div>
        </div>
        <div className="text-right">
          <h1 className="text-3xl font-extrabold tracking-tight text-brand">INVOICE</h1>
          <p className="mt-1 text-sm font-semibold text-slate-700">{invoice.invoice_number}</p>
        </div>
      </div>

      {/* Bill-to + dates */}
      <div className="grid grid-cols-2 gap-6 py-6">
        <div>
          <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Bill To</p>
          <p className="mt-1 font-semibold text-slate-800">{invoice.client_name}</p>
          {invoice.client_address && (
            <p className="text-sm text-slate-500 whitespace-pre-line">{invoice.client_address}</p>
          )}
          {invoice.client_vat && (
            <p className="text-sm text-slate-500">VAT: {invoice.client_vat}</p>
          )}
          <p className="text-sm text-slate-500">{getCountry(invoice.country_code).name}</p>
        </div>
        <div className="text-right">
          <div className="mb-2">
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Issue Date</p>
            <p className="text-sm font-medium text-slate-700">{invoice.issue_date}</p>
          </div>
          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Due Date</p>
            <p className="text-sm font-medium text-slate-700">{invoice.due_date || '—'}</p>
          </div>
        </div>
      </div>

      {/* Line item table */}
      <table className="w-full border-collapse">
        <thead>
          <tr className="bg-brand-50 text-left text-xs font-semibold uppercase tracking-wide text-brand">
            <th className="rounded-l-lg px-4 py-3">Description</th>
            <th className="px-4 py-3 text-right">Qty</th>
            <th className="px-4 py-3 text-right">Unit Price</th>
            <th className="rounded-r-lg px-4 py-3 text-right">Amount</th>
          </tr>
        </thead>
        <tbody>
          <tr className="border-b border-slate-100">
            <td className="px-4 py-4 text-sm text-slate-700">{invoice.service_description}</td>
            <td className="px-4 py-4 text-right text-sm text-slate-700">{invoice.quantity}</td>
            <td className="px-4 py-4 text-right text-sm text-slate-700">
              {formatMoney(invoice.unit_price, currency.code)}
            </td>
            <td className="px-4 py-4 text-right text-sm font-medium text-slate-800">
              {formatMoney(subtotal, currency.code)}
            </td>
          </tr>
        </tbody>
      </table>

      {/* Totals */}
      <div className="mt-6 flex justify-end">
        <div className="w-64 space-y-2">
          <div className="flex justify-between text-sm">
            <span className="text-slate-500">Subtotal</span>
            <span className="font-medium text-slate-800">{formatMoney(subtotal, currency.code)}</span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-slate-500">VAT ({Number(invoice.vat_rate) || 0}%)</span>
            <span className="font-medium text-slate-800">{formatMoney(vatAmount, currency.code)}</span>
          </div>
          <div className="flex justify-between border-t border-slate-200 pt-2 text-base font-bold text-brand">
            <span>Total</span>
            <span>{formatMoney(total, currency.code)}</span>
          </div>
          <p className="pt-1 text-xs text-slate-400">
            Currency: {currency.code} · Country: {country.name} ({country.code})
          </p>
        </div>
      </div>

      {/* Footer disclaimer */}
      <div className="mt-10 border-t border-slate-200 pt-4">
        <p className="text-[10px] leading-relaxed text-slate-400">{PDF_DISCLAIMER}</p>
      </div>
    </div>
  )
})

export default InvoicePreview
